version: '3.8'
services:
  web:
    container_name: web
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      DATABASE_URL: ${DB_DIALECT}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    depends_on:
      - ${DB_HOST}

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - my-mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    ports:
      - "8080:80"
    depends_on:
      - ${DB_HOST}

volumes:
  my-mysql-data:
  my-postgres-data:
