version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bruh
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-user-pw
      MYSQL_ROOT_HOST: '%'
    volumes:
      - my-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-dev
    ports:
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql

volumes:
  my-mysql-data: