services:
  # Database
  db:
    image: mysql:5.7
    container_name: timeoff_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kWtGMzj1G7U1DwAxRSq6Lv27DpVPVaoT9uLGvyy5
      MYSQL_DATABASE: timeoffmanagement
      MYSQL_USER: timeoff
      MYSQL_PASSWORD: kWtGMzj1G7U1DwAxRSq6Lv27DpVPVaoT9uLGvyy5
    ports:
      - 3306:3306
    networks:
      - timeoffnetwork
  # timeoff-management
  timeoff:
    depends_on:
      - db
    build: .
    container_name: timeoff
    restart: always
    volumes:
      - type: bind
        source: ./db.json
        target: /timeoff/config/db.json
      - type: bind
        source: ./app.json
        target: /timeoff/config/app.json
    ports:
      - 3000:3000
    networks:
      - tunnel
      - timeoffnetwork

networks:
  timeoffnetwork:
  tunnel:
    external: true

volumes:
  db_data:
