version: '3.8'
services:
  timeoff:
    container_name: time
    build: .
    environment:
      DB_HOST: "db"
      DB_DATABASE: "my-database"
      DB_USERNAME: "root"
      DB_PASSWORD: "my-secret-pw"
      DB_DIALECT: "mysql"
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config

  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-database
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-user-pw
      MYSQL_ROOT_HOST: '%'
    volumes:
      - my-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  my-mysql-data:
